### ISSUE TITLE
Articolo lancio Internet Health Report

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/Articoli-Post-mozilla-italia#1]
# Proposta di Articolo o Post per la comunità di Mozilla Italia

Tipo di Inserimento:

* [X] Creazione di un nuovo articolo/post
* [ ] Segnalazione Bug su articoli già pubblicati

## Indicare per quale canale di Mozilla Italia si propone il contenuto o si segnala il problema:

 * [ ] Facebook
 * [ ] Twitter
 * [X] Blog di Mozilla Italia

Inserire nei commenti la natura della richiesta o il testo proposto.
Grazie del tuo contributo.

Tutta la comunità di Mozilla Italia

**Comment by edovio** [comment]
Testo Proposto:

Che cosa in questo momento sta bloccando e cosa sta aiutando la crescita di Internet per miliardi di utenti?
Ieri Mozilla ha pubblicato la nuova versione del resoconto sullo stato di salute di internet. All’indirizzo http://mzl.la/ihr è possibile scoprire in dettaglio il contenuto del resoconto e conoscere come poter esser coinvolti nella sua realizzazione futura.

Il lavoro è suddiviso in cinque tematiche principali che sono:
 - Decentralization (Decentralizzazione tecnologica), ossia, chi sta controllando Internet?

 - Digitalinclusion (Inclusione Digitale), ossia, chi ha accesso alla rete?

 - Openness (Apertura tecnologica), ossia, le tecnologie utilizzate per creare Internet quanto sono “aperte”? 

- Privacy&Security (Privacy e Sicurezza), ossia, Internet è sicuro? 

- Webliteracy (Alfabetizzazione digitale nelle tecnologie del Web), ossia, chi ha l’opportunità di poter creare la propria esperienza online?

All’interno di ogni tematica sono contenute tutte le informazioni per comprenderne meglio il significato e leggere le storie e le esperienze globali che hanno inspirato le azioni di milioni di volontari in tutto il mondo nella salvaguardia dell’apertura, dell’inclusione e della pari opportunità di creare la propria esperienza nel web liberamente. 

Oggi giorno, ognuno di noi è chiamato a riflettere su come Internet e il Web siano sempre più centrali nella nostra quotidianità. Il resoconto, pertanto, non vuole essere un documento statico ma una pari opportunità di condivisione e di coinvolgimento nell’interesse comune di miliardi di persone nel mondo di poter perseguire liberamente la propria esperienza in Internet. 
Per maggiori informazioni e scoprire come esser coinvolto visita il sito internet http://mzl.la/ihr o entra in contatto con la comunità Italiana.

**Comment by kitsunenosaraT** [comment]
Testo revisionato

Che cosa in questo momento sta ostacolando la crescita di Internet per miliardi di utenti? E cosa invece la sta aiutando?
**[Ieri?]** Mozilla ha pubblicato la nuova versione del Rapporto sullo stato di salute di Internet. All’indirizzo http://mzl.la/ihr è possibile leggere in dettaglio il contenuto del rapporto e scoprire come collaborare alle sue versioni future.

Il rapporto si articola in cinque tematiche principali:

* Decentralization (Decentramento tecnologico), ossia, chi sta controllando Internet?

* Digital Inclusion (Inclusione digitale), ossia, chi ha accesso alla rete?

* Openness (Apertura tecnologica), ossia, quanto sono “aperte” le tecnologie utilizzate per creare Internet?

* Privacy & Security (Privacy e sicurezza), ossia, Internet è sicuro?

* Web Literacy (Alfabetizzazione digitale nelle tecnologie del Web), ossia, chi ha l’opportunità di plasmare la propria esperienza online?

All’interno di ogni area tematica si trovano informazioni per comprenderne meglio il significato e la portata, ma soprattutto le storie e le esperienze globali che hanno inspirato le azioni di milioni di volontari in tutto il mondo per salvaguardare l’apertura, l’inclusione e la pari opportunità di creare la propria esperienza nel Web liberamente.

Oggigiorno ognuno di noi è chiamato a riflettere su come Internet sia sempre più centrale nella nostra quotidianità. Il rapporto, pertanto, non vuole essere un documento statico ma una pari opportunità di condivisione e di coinvolgimento nell’interesse comune di miliardi di persone nel mondo per perseguire liberamente la propria esperienza in Internet.

Per scoprire di più e contribuire al rapporto con la tua esperienza visita il sito internet http://mzl.la/ihr o entra in contatto con la comunità italiana.

Diff: https://www.diffchecker.com/zf4vdHfy

**Comment by kitsunenosaraT** [comment]
Piccola proposta di miglioramento: se carichiamo il file direttamente su GitHub e lo modifichiamo tramite pull request, possiamo ricavara il diff direttamente senza usare risorse esterne.

**Comment by edovio** [comment]
In realtà questo articolo l'ho realizzato in estrema fretta per poterlo pubblicare la settimana scorsa ma alla fine siamo andati lunghi.
Dopo la revisione l'idea è proprio quella di realizzare il file md. :) ma per evitare mille pull request ho pensato fosse più comodo fare la revisione qui. Se vogliamo possiamo creare l'issue e poi indicare qui la pull request a cui fa riferimento.

**Comment by edovio** [comment]
Titolo: Lancio del nuovo rapporto sullo stato di salute di Internet

Testo Definitivo: 
Che cosa in questo momento sta ostacolando la crescita di Internet per miliardi di utenti? E cosa invece la sta aiutando?
Mozilla ha pubblicato la nuova versione del Rapporto sullo stato di salute di Internet. All’indirizzo http://mzl.la/ihr è possibile leggere in dettaglio il contenuto del rapporto e scoprire come collaborare alle sue versioni future.

Il rapporto si articola in cinque tematiche principali:

  *  Decentralization (Decentramento tecnologico), ossia, chi sta controllando Internet?

   * Digital Inclusion (Inclusione digitale), ossia, chi ha accesso alla rete?

   * Openness (Apertura tecnologica), ossia, quanto sono “aperte” le tecnologie utilizzate per creare Internet?

   * Privacy & Security (Privacy e sicurezza), ossia, Internet è sicuro?

   *  Web Literacy (Alfabetizzazione digitale nelle tecnologie del Web), ossia, chi ha l’opportunità di plasmare la propria esperienza online?

All’interno di ogni area tematica si trovano informazioni per comprenderne meglio il significato e la portata, ma soprattutto le storie e le esperienze globali che hanno inspirato le azioni di milioni di volontari in tutto il mondo per salvaguardare l’apertura, l’inclusione e la pari opportunità di creare la propria esperienza nel Web liberamente.

Oggigiorno ognuno di noi è chiamato a riflettere su come Internet sia sempre più centrale nella nostra quotidianità. Il rapporto, pertanto, non vuole essere un documento statico ma una pari opportunità di condivisione e di coinvolgimento nell’interesse comune di miliardi di persone nel mondo per perseguire liberamente la propria esperienza in Internet.

Per scoprire di più e contribuire al rapporto con la tua esperienza visita il sito internet http://mzl.la/ihr o entra in contatto con la comunità italiana.

**Comment by gioxx** [comment]
Pubblicato: https://www.mozillaitalia.org/home/2018/04/17/mozilla-internet-health-report/

**Comment by edovio** [comment]
Creata Pull Request #2 dell'articolo pubblicato in data odierna.

**Comment by edovio** [comment]
Documento caricato sul Repository
