### ISSUE TITLE
Articolo OSB

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/Articoli-Post-mozilla-italia#3]
# Proposta di Articolo o Post per la comunità di Mozilla Italia

Tipo di Inserimento:

* [X] Creazione di un nuovo articolo/post
* [ ] Segnalazione Bug su articoli già pubblicati

## Indicare per quale canale di Mozilla Italia si propone il contenuto o si segnala il problema:

* [ ] Facebook
* [ ] Twitter
* [X] Blog di Mozilla Italia

Inserire nei commenti la natura della richiesta o il testo proposto.

Grazie del tuo contributo da parte di
Tutta la comunità di Mozilla Italia

**Comment by edovio** [comment]
Informazioni da parte di chi ha scritto l'articolo (@Mte90 )
L'articolo dovrebbe seguire l'ordine delle domande: inizio motivare le persone a leggere e poi verso la fine gli approfondimenti e poi come partecipare
La revisione dell'italiano avverrà in questo documento e la risposta alle domande può essere articolata anche in fusione, tutto dipenderà dalla quantità delle stesse
Testo:
https://github.com/edovio/Open_Student_Book
Daniele Scasciafratte intervista Edoardo Viola, che si occupa della partecipazione nella comunità e segue diversi programmi come il Mozilla Campus Club. 
Il progetto Open Student Book è stato il primo presentato da lui per Open Leadership ed ora è mentor in questo programma.

    Che cosa significa "open source" per uno studente universitario non informatico?

    Quando ho iniziato a portare avanti questo progetto con i primi volontari che venivano dal mondo informatico-ingegneristico non avevamo la più pallida idea di che cosa significasse per gli altri studenti "open source". 

    È proprio per questa ragione che abbiamo deciso di creare questo strumento. Col tempo, con la ricerca e con le persone intervistate (sì, abbiamo fatto dei sondaggi per raccogliere informazioni) nei primi mesi di sviluppo abbiamo pian piano trovato una risposta (preliminare???) a questa domanda. Non avevano idea di che cosa fosse. 

    Pian piano dunque, verificando i piani di studio, abbiamo articolato delle risposte e soprattutto delle motivazioni interessanti che aiutino a comprendere cosa sia l'open source e le sue applicazioni in tutte le possibili aree di studio. Per esempio, oggigiorno un futuro economo, vede nella creazione di una community un ottimo strumento per creare Rete, per un fisico rappresenta uno strumento utile nella diffusione e sperimentazione delle ricerche (un esempio https://it.wikipedia.org/wiki/Lista_dei_progetti_di_calcolo_distribuito), per un futuro psicologo per  sperimentare a livello psicometrico determinate teorie e la lista potrebbe ancora allungarsi, ma soprattutto il comune denominatore è sviluppare abilità e produrre conoscenza in modo libero e accessibile a chiunque nel mondo.

    Che cosa significa invece per chi non viene dal mondo informatico? (qualche esempio)

    In generale l'open source veniva visto, soprattutto in passato, come qualcosa di gratis e accessibile a tutti, che però non aveva alcuna potenzialità se non quella di fare beneficenza. 

    Oggi le cose stanno cambiando e ci si rende sempre più conto del potenziale dell'open source, specialmente grazie alle comunità che si stanno sviluppando in tutto il globo. L'open source garantisce il facile accesso alla tecnologia, all'informazione, all'innovazione e all'opportunità di fare del business solidale. Tutte opportunità che sono nate grazie anche ad un accesso libero, aperto e inclusivo della risorsa oggigiorno più importante: Internet. 

    Gli esempi più eclatanti sono Wikipedia, che garantisce un facile accesso a materiale informativo, WordPress che permette a chiunque di realizzare una propria presenza nel Web con estrema facilità, LibreOffice che offre una suite completa per l'ufficio senza limitazioni di piattaforma... Gli esempi sono a migliaia e ogni giorno nascono nuovi progetti che hanno la volontà di innovare e soddisfare i bisogni dell'uomo moderno.

    Perché l'open source è importante nel mondo?

    Perché permette di mettere al centro dell'idea l'uomo, piuttosto che il business puro. 

    Permette all'uomo di accrescere le proprie competenze, di creare delle comunità e di portare innovazione in tutti i settori esistenti con pochissime risorse. 

    Sviluppa e crea nuove idee, le convalida e le mette in atto con il supporto di altri che credono sino infondo nella mission del progetto. 

    Oggigiorno è fondamentale ripercorrere i passi che nel 1700 i grandi della Storia hanno dovuto percorrere per far sì che l'uomo abbia gli strumenti giusti per rendersi più autonomo e libero. 

    Che cosa è la metologia open source?

    La metologia open source è quella che garantisce la trasparenza sia in fase di progettazione e sviluppo che in fase di revisione di un progetto e permette a chiunque di prender parte ad un progetto in modo del tutto libero e inclusivo. 

     I progetti vengono sviluppati da un team di persone (comunità) e le attività vengono coordinate da un "leader" del progetto che ha la funzione di mettere in atto le decisioni necessarie, in armonia con le necessità della stessa comunità. Il prodotto di questi progetti tipicamente viene distribuito con delle licenze open che garantiscono sia la trasparenza del prodotto finale che la regolamentazione al suo utilizzo.

    Perché è importante per uno studente? (citare mondo lavorativo)

    Perché tipicamente, soprattutto in Italia, c'è una estrema differenza tra le conoscenze acquisite durante i percorsi universitari e le abilità richieste nel mondo del lavoro. 

    Oggigiorno dobbiamo necessariamente affrontare un mercato del lavoro sempre più esigente. Con questa ottica, contribuire e far parte di progetti open source può garantire a tutti coloro che vogliono vedere applicate le conoscenze acquisite, o che si stanno acquisendo nei percorsi universitari, una alternativa gratuita, coinvolgente, di congregazione e professionalizzante, al lavoro nero, sotto pagato o gratuito per società o altre attività che hanno l'obiettivo di ottenere prestazioni lavorative a basso costo a discapito della formazione e della professionalizzazione dell'individuo. 

    Perché hai voluto fare un libro? E poi in modo collaborativo?

    Perché il libro è la risorsa che storicamente è sempre stata utilizzata come metodologia standard per la divulgazione di contenuti. Il libro attualmente è disponibile per tutti i formati supportati dagli E-Reader e sulla piattaforma GitBook consultabile da qualunque PC, tablet o smartphone.

    Aver realizzato questo progetto in modo collaborativo non è stata solo una necessità ma una volontà ideologica. Il Libro parla di open source e di progetti collaborativi e di come essi siano interessanti e utili per gli studenti universitari. Non poteva che esser fatto in modo collaborativo, naturalmente.

    Sei quindi riuscito a coinvolgere studenti di diverse facoltà in tutta Italia?

    Sì, a tutt'oggi gli studenti coinvolti nella stesura della prima revisione provengono da tre università Italiane e da cinque differenti corsi di laurea. 

    Il progetto è solo in Italiano?

    No, al momento è stata realizzata anche una versione in inglese e in futuro l'idea è quella di realizzare un progetto che contempli più modelli universitari nel mondo. 

    Perché questo progetto è stato presentato ad Open leadership (Suppongo volessi dire Mozilla Global Sprint 2017)?

    L'intenzione è quella di internazionalizzare il progetto al fine di offrire delle risorse utili non soltanto a un contesto Italiano ma europeo e magari, perché no, un giorno globale.

    Come si contribuisce al progetto?

    Basta visitare la pagina ufficiale del progetto https://edovio.github.io/Open_Student_Book e leggere "CONTRIBUTING.md", il documento che illustra le modalità con cui contribuire. Il progetto al momento si trova in un repository pubblico sulla piattaforma GitHub.

    Come contribuire in modo veloce: qualche link di esempio.

    https://github.com/edovio/Open_Student_Book/issues In questa pagina è possibile visionare i principali argomenti su cui si può contribuire, provando, proponendo modifiche o traducendo il progetto in differenti lingue.

    Come pensi sarà questo libro fra un anno?

    Tra un anno la volontà è quella di creare non soltanto un libro ma un sito Internet dove gli studenti universitari possano conoscere i motivi per i quali noi crediamo nell'open source e i progetti che prevedono il coinvolgimento degli stessi studenti universitari nello sviluppo. In questo modo cerchiamo di indirizzare in modo efficace gli studenti verso una fantastica esperienza nei progetti open source.

**Comment by Mte90** [comment]
Qualche problema con github (ho voluto usare l'interfaccia ma alla fine ho optato per la linea di comando).

**Comment by edovio** [comment]
La revisione sarà fatta direttamente sul file all'interno della Pull Request
