### ISSUE TITLE
Post Social sullo sprint Common Voice

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/Articoli-Post-mozilla-italia#5]
# Proposta di Articolo o Post per la comunità di Mozilla Italia

Tipo di Inserimento:

* [X] Creazione di un nuovo articolo/post
* [ ] Segnalazione Bug su articoli già pubblicati

## Indicare per quale canale di Mozilla Italia si propone il contenuto o si segnala il problema:

* [X] Facebook
* [X] Twitter
* [ ] Blog di Mozilla Italia

Inserire nei commenti la natura della richiesta o il testo proposto.

Grazie del tuo contributo da parte di
Tutta la comunità di Mozilla Italia

**Comment by edovio** [comment]
Testo proposto:
Da ieri è disponibile all'indirizzo web: https://voice-sprint.mozilla.community il sito dove è possibile contribuire al progetto Common Voice! Per tutto il fine settimana il Canale su Telegram "Home" di Mozilla Italia diventa  la "Casa" delle vostre segnalazioni e delle vostre contribuzioni al progetto (Link Canale: https://t.me/joinchat/BCql3UMy26nl4qxuRecDsQ) !!!

**Comment by Sav22999** [comment]
Invece di "Canale su Telegram "Home" di Mozilla Italia" non suonerebbe meglio "Canale "Home" di Mozilla Italia, su Telegram,"?

**Comment by edovio** [comment]
Si va benissimo :)
